### PR TITLE
Fixes total row in research trends report.

### LINKED ISSUE #323: In the "Research Trends Report", the "TOTAL" row on the bottom is always showing zero

### PR DESCRIPTION
**Pull request by justinlittman**
closes #323

### CODE REVIEW

File: app/services/research_trends_report_generator.rb [hunk 1]
```diff
@@ -81,8 +81,8 @@ def generate_totals(years_totals)
     totals_row = ['TOTAL']
     grand_total = 0
     Range.new(start_year, end_year).each do |year|
```
Comment (jcoyne) [inline app/services/research_trends_report_generator.rb]: Should we cast `start_year` & `end_year` `#to_i`?

Comment (justinlittman) [reply app/services/research_trends_report_generator.rb]: Concur. Fixed.
